name: Trigger auto deployment for inventariofarmacia-app-202210181

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/inventariofarmacia-app-202210181-AutoDeployTrigger-7bd88c02-015d-404c-9ded-7d70b3cc1f79.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: inventariofarmacia20221018151957.azurecr.io
          username: ${{ secrets.INVENTARIOFARMACIAAPP202210181_REGISTRY_USERNAME }}
          password: ${{ secrets.INVENTARIOFARMACIAAPP202210181_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: inventariofarmacia20221018151957.azurecr.io/inventariofarmacia-app-202210181:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.INVENTARIOFARMACIAAPP202210181_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n inventariofarmacia-app-202210181 -g DefaultResourceGroup-CUS --server inventariofarmacia20221018151957.azurecr.io --username  ${{ secrets.INVENTARIOFARMACIAAPP202210181_REGISTRY_USERNAME }} --password ${{ secrets.INVENTARIOFARMACIAAPP202210181_REGISTRY_PASSWORD }}
            az containerapp update -n inventariofarmacia-app-202210181 -g DefaultResourceGroup-CUS --image inventariofarmacia20221018151957.azurecr.io/inventariofarmacia-app-202210181:${{ github.sha }}
